from datetime import datetime, timedelta
import ahocorasick
from pyrogram import filters, enums
from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup

from Banword import Banword as app

# List of 18+ or abusive words (expandable)
BAD_WORDS = [
    # 18+ related words
    "18+",
    "sex",
    "porn",
    "nude",
    "blowjob",
    "boobs",
    "bobs",
    "condom",
    "xxx",
    "adult",
    "Demo 1 pic free",
    "nangi",
    "randi",
    # Common gaaliyan & offensive words (Hindi/English)
    "chutiya",
    "madarchod",
    "bhenchod",
    "gaand",
    "gand",
    "lund",
    "ch**d",
    "g***i",
    "harami",
    "kutte",
    "boor",
    "chuchi",
    "kutta",
    "gandu",
    "madharchod",
    "lundoo",
    "lodu",
    "bhains",
    "chod",
    "randi",
    "randa",
    "haramzada",
    "randi ka bacha",
    "bhosdiwala",
    "bhosdike",
    "mc",
    "mcchod",
    "randi ki aulaad",
    "gand mara",
    "lund mar",
    "lauda",
    "loda",
    "chodu",
    "chut",
    "chutiyapa",
    "chutiye",
    "chut ke",
    "chut ke laude",
    "chut ke bache",
    "bhosadike",
    # Slang variations with stars (to catch censored forms)
    "ch**d",
    "g***i",
    "m**ch*d",
    "b**chod",
    "b***chod",
] + [
    "sex",
    "porn",
    "nude",
    "fuck",
    "bitch",
    "dick",
    "pussy",
    "slut",
    "boobs",
    "cock",
    "asshole",
    "chudai",
    "rand",
    "chhinar",
    "sexy",
    "hot girl",
    # ✅ Common Hindi Gaaliyan in English Font
    "chutiya",
    "madarchod",
    "Madhrachod",
    "Madharchod",
    "betichod",
    "behenchod",
    "gandu",
    "randi",
    "bhosdi",
    "hijda",
    "lund",
    "chod",
    "jhaatu",
    "harami",
    "kamina",
    "saala",
    "gand",
    "pagal",
    "bhadwa",
    "chut",
    "bevkoof",
    "nikkamma",
    "haramkhor",
    "chaalu",
    "fattuu",
    "dhakkan",
    "gadha",
    "kutta",
    "suvar",
    "besharam",
    "bhosdike",
    "teri maa ki chut",
    "teri behan ki chut",
    "randi ka bacha",
    "chinal ka bacha",
    "gb road pe teri ma show karti",
    "gb road ke paidaish",
    "teri ma ka boor",
    "teri ma ka boor fadhu",
    "teri ma ki chut mai ungali kardu",
    "teri bahan ki chut fadhu",
    "teri bahan ki gand mai ungali karu",
    "teri bahan ki boor ungali karu",
    "teri bahan meri rakhail",
    "teri ma meri rakhail",
    "Dm karo baby",
    "Inbox karo baby",
    "private group chalogi baby",
    "tera porn banauga",
    "tera hot video viral karunga",
    "Ruk Madhar chodh",
    "sale",
    "Randi ke pille tore ma ko chodho",
    "chutad",
    "haramzaada",
    "haram ki aulaad",
    "suvar ka baccha",
    "gand ka keeda",
    "chirkut",
    "ghatiya",
    "sadela",
    "choor",
    "lutera",
    "chichora",
    "badtameez",
    "baddimag",
    "fraud",
    "nalayak",
    "bewda",
    "sandass",
    "ganda",
    "dhongi",
    "bhikhari",
    "faltu",
    "kachra",
    "pagal kutta",
    "badmash",
    "aalsi",
    "kanjoos",
    "ghamandi",
    "farzi",
    "dhurt",
    "bakchod",
    "gappi",
    "nakli",
    "chalu",
    "lafanga",
    "bakwas",
    "bikau",
    "chapri",
    "nalla",
    "tatti",
    "jhantu",
    "ullu ka pattha",
    "ulloo",
    "chindi",
    "panauti",
    "lukkha",
    "kuttiya",
    "kaminey",
    "kamzarf",
    "budbak",
    "chirkut",
    "sust",
    "tharki",
    "bhagoda",
    "kutta kamina",
    "Madharchodh apni ma mat chuda",
    "tera bap gay hain sayad",
    "Madharchodh apni bahan mat chuda",
    "Hello koi ladki chudegi",
    "bhains ki aankh",
    "teri taang tod dunga",
    "teri band baja dunga",
    "tera dimaag kharab hai",
    "teri waat laga dunga",
    "teri maa ka bhosda",
    "Hello koi ladki chudegi"
    "Free me kuch dekh na ho to ajao",
    "Kisi ladki ka ko video chahiye ho to message kro",
    "Teri mmmaaaaa kaaaa bhooosssssddddddaaaaaaa",
    "Tu apni ma chudwa le paise de dunga",
    "Mere pass aayhe mera hatiyaar bhot aacha h aao Dm kro bhabhiyo",
    "Mother chor",
    "Girls chahiye dm me",
    "Se x x x gif  chat ttt kregi koi dmm kooo",
    "Jo bhabhi satisfied nhi hui hai yha",
    "Tum Johny sin ke lannddd ka bal Ho",
    "Koi ladki h jo baat karegi   paani  na nikal du to bolnaaa",
    "H koii mood m",
    "Koi bhabhi h jo 8 inch tool here any house wife jo pyasi ho",
    "Kisi larki ko apna paani nikalwana hai toh ajaie",
    "Hila rha hu koi dekhogi msg kro",
    "yaha koi bhabhi ya sister hai kya",
    "teri gaand maar dunga",
    "Teri Maa ka doodh laa laa jaldii",
    "Teri ma ki surang dekhi maine",
    "Vc aa Teri Maa ki chuut",
    "Teri ma ka kya ghufa hai kya",
    "Koi boy mera friend  ya bestu ya boy friend banega",
    "teri ma ko patak ke chodh dunga",
    # ✅ Common Porn & NSFW Terms (Mix of Hindi & English)
    "sex",
    "porn",
    "nude",
    "nangi",
    "chudai",
    "bhabhi chudai",
    "sex chat",
    "sex chat karogi",
    "sex chat karogi baby",
    "Koi achhi ldki hai kya jo bat krna chahegi",
    "Free earning krne k liye msg kro",
    "All type video available jisko chahiye just aao fast",
    "lund",
    "gaand",
    "bhosda",
    "chut",
    "maal",
    "jism",
    "randi",
    "randi khana",
    "desi sex",
    "hot video",
    "nangi ladki",
    "bhabhi nudes",
    "bhabhi sex",
    "sexy aunty",
    "nude aunty",
    "bhabhi ki chut",
    "real meet",
    "viral video",
    "rape video",
    "nudes viral",
    "aunty ki chut",
    "Koi achhi ldki hai kya jo bat krna chahegi",
    "Free earning krne k liye msg kro",
    "Here's 8 inches for you gujju boy",
    "Come on inbox",
    "audio call",
    "Boy to boy dm me",
    "Any girl for call",
    "Any girl for call then dm me",
    "Want service and exclusive video So Dm me fast",
    "Boops",
    "Any sugar mommy here or 20+ female",
    "Need boyfriend",
    "Dirtyy talkss with giffs",
    "Any one women for fun chat",
    "MESSAGE ME FAST BABY",
    "Message me personally",
    "DM me for service",
    "gils cann dmmm me",
    "Any cut guy here",
    "All groups available dm me",
    "Any girl from Lucknow in this group",
    "Any girl from delhi in this group",
    "Any girl from Mumbai in this group",
    "Any girl from Up in this group",
    "My Milky Girlfriend Pics",
    "Available now",
    "I need girlfriend",
    "Boy's come inbox",
    "boobs",
    "Dakho biioo aa jao obbii..oo aa jao",
    "Unsatisfy girl",
    "I want service message me",
    "I'm available came boy",
    "Wife swapping",
    "Msg me",
    "Really meet only girls",
    "tits",
    "nipple",
    "dildo",
    "pussy",
    "vagina",
    "penis",
    "cock",
    "dick",
    "cum",
    "anal",
    "squirt",
    "deepthroat",
    "hentai",
    "bdsm",
    "lesbian",
    "gay sex",
    "futa",
    "69",
    "screwing",
    "sex chat",
    "incest",
    "stepmom",
    "stepsis",
    "stepbro",
    "honeymoon sex",
    "bhabhi nude",
    "hot indian actress",
    "bio links join all girls",
    "join bio link",
    "bio link join",
    "join my chatting group",
    "join viral video channel",
    "join rape video channel",
    "join naughty group",
    "desi nudes",
    "Wife swapping",
    "Need boyfriend",
    "I'm available came boy",
    "Really meet only girls",
    "Msg me boys",
    "Genuine boys dm",
    "Mom lover dm",
    "Bhabhi lover dm",
    "Aunty lover dm",
    "Gay dm me",
    "sexy saree",
    "lingerie",
    "erotic",
    "kinky",
    "naughty",
    "sensual",
    "lust",
    "muth",
    "muthi",
    "masturbation",
    "call girl",
    "escort",
    "sex worker",
    "rape porn",
    "forced porn",
    "underage porn",
    "child porn",
    "pedo",
    "loli",
    "teen sex",
    "schoolgirl porn",
    "hijab porn",
    "casting couch",
    "sex tape",
    "strip club",
    "naked",
    "uncensored",
    "bikini photos",
    "hot saree",
    "sexy photos",
    "onlyfans",
    "patreon nudes",
    "hot cam",
    "sex cam",
    "live sex",
    "private parts",
    "exposed",
    "naked selfie",
    "sex video",
    "desi sex video",
    "bollywood sex",
    "lingam massage",
    "tantra sex",
    "milf",
    "hotwife",
    "swinger",
    "erotic massage",
    "boobs press",
    "licking",
    "lick pussy",
    "moaning",
    "dirty talk",
    "hot girl",
    "big boobs",
    "tight pussy",
    "wet pussy",
    "hard cock",
    "big cock",
    "service available",
    "paid service available",
    "blowjob",
    "I am ready message me",
    "Boy's come inbox",
    "I need girlfriend for sex chat",
    "I'm full nude now",
    "Paid show",
    "video call available",
    "fuck you",
    "fuck me",
    "pussy",
    "boobs",
    "handjob",
    "sexy dance",
    "strip tease",
    "sex position",
    "saree sex",
    "sexy aunty video",
    "hot desi bhabhi",
    "bollywood hot",
    "item girl",
    "hot indian model",
    "desi randi",
    "desi call girl",
    "sexy night",
    "hijra sex",
    "chudai story",
    "sex story",
    "suhagraat sex",
    "honeymoon night",
    "love making",
    "hot romance",
    "desi romance",
    "hot chat",
    "sexy time",
    "naughty chat",
    "dirty video",
    "hidden cam",
    "bathroom sex",
    "hotel sex",
    "massage sex",
    "body to body massage",
    "saree romance",
    "Hyy everyone I need cute girl friend ant girl here",
    "Married ladies can you send me a message To chat",
    "Any girl want to roleplay dm only genuine girls",
    "Mkc",
    "Tmc",
    "bkl",
    "Mkl",
    "choli romance",
    "cleavage show",
    "hot navel",
    "desi thighs",
    "big ass",
    "backside show",
    "With face fingaring no xtra charges",
    "Full open service",
    "plzzz commmmm tooooo myyy biiioooo gyyzzz",
    "Yt premium available",
    "Mom sister sleeping group is available at low price",
    "Dad body guy with a plus size D interested gorgeous ladies Please DM",
    "Cm show available dm",
    "I m uncle genuine girl cone",
    "Anyone want to enjoy mutual then come",
    "Low rate videos available please DM",
    "Paid videos available anyone need please DM",
    "Low rate videos available please DM",
    "Sleeping pills grp available",
    "Free now",
    "uncle here only female gil come",
    "I'm well educated bull looking good",
    "any couple want some  gang bang cuckolding and pregnancy",
    "I'm genuine experience m bull from",
]

AC = ahocorasick.Automaton()
for idx, word in enumerate(BAD_WORDS):
    AC.add_word(word.lower(), (idx, word))
AC.make_automaton()

cache = {}
CACHE_TTL = timedelta(minutes=10)

def contains_bad_word(text):
    return any(True for _ in AC.iter(text.lower()))

async def get_admins(chat_id):
    now = datetime.utcnow()
    if chat_id in cache:
        entry = cache[chat_id]
        if now < entry["expires"]:
            return entry["admins"]

    admins = []
    async for m in app.get_chat_members(chat_id, filter=enums.ChatMembersFilter.ADMINISTRATORS):
        admins.append(m.user.id)

    cache[chat_id] = {"admins": admins, "expires": now + CACHE_TTL}
    return admins

@app.on_message(filters.group & filters.text & ~filters.via_bot)
async def filter_18(client, message):
    text = (message.text or message.caption or "").lower().strip()
    if not text or not message.from_user:
        return

    if not contains_bad_word(text):
        return

    admin_ids = await get_admins(message.chat.id)

    if message.from_user.id in admin_ids:
        return

    try:
        await message.delete()
    except Exception:
        return

    warn_text = f"{message.from_user.mention}, ᴀʙᴜsᴇ ᴀɴᴅ 18+ ᴍᴇssᴀɢᴇs ᴀʀᴇ ɴᴏᴛ ᴀʟʟᴏᴡᴇᴅ!"
    btn = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton("ᴜᴘᴅᴀᴛᴇ", url="https://t.me/TwsAssociation"),
                InlineKeyboardButton("sᴜᴘᴘᴏʀᴛ", url="https://t.me/TwsSupportGroup"),
            ]
        ]
    )
    await message.reply(warn_text, reply_markup=btn)
